name: calculator
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:


dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
